apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: resource-git-petclinic
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/luisfy86/petclinic_tekton.git
    - name: sslVerify
      value: "false"
